import type { TaxProfileInput } from "./types"

type TaxProfileInputOverrides = Pick<
  TaxProfileInput,
  "grossIncome" | "payFrequency" | "customDeductions"
>
type TaxProfilePassthrough = Omit<TaxProfileInput, "grossIncome" | "payFrequency">
type TaxProfileLike = Partial<TaxProfilePassthrough>

const TAX_PROFILE_INPUT_KEYS = [
  "dependents",
  "federalMultipleJobsCheckbox",
  "federalStep3Credits",
  "federalOtherIncome",
  "federalDeductions",
  "federalExempt",
  "stateWithholdingExemptions",
  "marylandWithholdingExemptions",
  "delawareWithholdingExemptions",
  "hawaiiWithholdingExemptions",
  "maineWithholdingExemptions",
  "minnesotaWithholdingExemptions",
  "nebraskaWithholdingExemptions",
  "southCarolinaWithholdingExemptions",
  "districtOfColumbiaWithholdingExemptions",
  "vermontWithholdingExemptions",
  "westVirginiaWithholdingExemptions",
  "wisconsinWithholdingExemptions",
  "alabamaExemptionCode",
  "arkansasExemptions",
  "arkansasLowIncomeRates",
  "idahoAllowances",
  "idahoAdditionalWithholding",
  "idahoExempt",
  "iowaAllowanceAmount",
  "iowaAdditionalWithholding",
  "iowaExempt",
  "iowaSpouseHasIncome",
  "iowaMilitarySpouseExempt",
  "kansasAllowanceRate",
  "kansasAdditionalWithholding",
  "kansasExempt",
  "louisianaDeductionClaim",
  "mississippiExemptionAmount",
  "mississippiSpouseEmployed",
  "missouriSpouseDoesNotWork",
  "newMexicoHigherSingleRate",
  "newMexicoExempt",
  "newMexicoMilitarySpouseExempt",
  "newMexicoNativeAmericanExempt",
  "oklahomaAllowances",
  "oklahomaHigherSingleRate",
  "oklahomaAdditionalWithholding",
  "oklahomaExempt",
  "oklahomaMilitarySpouseExempt",
  "oklahomaMilitaryIncomeExempt",
  "arizonaWithholdingPercent",
  "arizonaExempt",
  "californiaRegularAllowances",
  "californiaEstimatedDeductionAllowances",
  "connecticutWithholdingCode",
  "connecticutAdditionalWithholding",
  "connecticutReducedWithholding",
  "connecticutNonresidentApportionmentPercent",
  "connecticutFifteenDayExempt",
  "coloradoDeductionAmount",
  "districtOfColumbiaExempt",
  "georgiaAllowanceCount",
  "georgiaMarriedBothWorking",
  "hawaiiHigherSingleRate",
  "hawaiiCertifiedDisabled",
  "hawaiiNonresidentMilitarySpouse",
  "illinoisAllowanceLine1",
  "illinoisAllowanceLine2",
  "indianaPersonalExemptions",
  "indianaDependentExemptions",
  "indianaFirstTimeDependentExemptions",
  "indianaAdoptedChildExemptions",
  "indianaAdditionalStateWithholding",
  "indianaAdditionalCountyWithholding",
  "indianaNonresidentThirtyDayExempt",
  "indianaNonresidentMilitarySpouseExempt",
  "massachusettsExemptions",
  "massachusettsBlindExemptions",
  "massachusettsFullTimeStudentExempt",
  "massachusettsMsrraExempt",
  "massachusettsAdditionalWithholding",
  "maineHigherSingleRate",
  "michiganExemptions",
  "montanaBothSpousesWorking",
  "montanaExempt",
  "nebraskaExempt",
  "newJerseyRateTable",
  "newJerseyAllowances",
  "newJerseyExempt",
  "newYorkAdditionalStateWithholding",
  "newYorkExempt",
  "northCarolinaAllowances",
  "ohioExemptions",
  "ohioAdditionalStateWithholding",
  "ohioResidentMilitaryOutsideOhioExempt",
  "ohioNonresidentMilitaryExempt",
  "ohioNonresidentMilitarySpouseExempt",
  "ohioStatutoryExempt",
  "oregonAllowances",
  "oregonAdditionalWithholding",
  "oregonHigherSingleRate",
  "oregonExempt",
  "southCarolinaExempt",
  "westVirginiaLowerRateElection",
  "virginiaPersonalExemptions",
  "virginiaAgeBlindExemptions",
  "virginiaExempt",
  "state",
  "residenceState",
  "workState",
  "residenceCounty",
  "workCounty",
  "residenceCity",
  "workCity",
  "postalCode",
  "schoolDistrictId",
  "localTaxJurisdictionIds",
  "ohioSchoolDistrictNumber",
  "ohioSchoolDistrictIncomeTaxRate",
  "ohioMunicipalIncomeTaxRate",
  "ohioJeddJedzIncomeTaxRate",
  "oregonMetroLocation",
  "oregonMultnomahCountyLocation",
  "oregonMetroWithholdingElection",
  "oregonPfaWithholdingElection",
  "newYorkLocality",
  "newYorkWithholdingExemptions",
  "pennsylvaniaResidentPsdCode",
  "pennsylvaniaResidentEitRate",
  "pennsylvaniaWorkPsdCode",
  "pennsylvaniaWorkNonResidentEitRate",
  "rhodeIslandAllowances",
  "rhodeIslandAdditionalWithholding",
  "rhodeIslandExemptStatus",
  "reciprocityElection",
  "multiStateWorker",
  "retirement401kType",
  "retirement401kPercent",
  "retirement401kFlat",
  "insurancePremium",
  "insurancePreTax",
  "additionalFederalWithholding",
  "additionalStateWithholding",
  "pfmlPercent",
  "waCaresPercent",
] as const satisfies readonly (keyof TaxProfilePassthrough)[]

export function buildTaxProfileInput(
  profile: TaxProfileLike,
  overrides: TaxProfileInputOverrides
): TaxProfileInput {
  const input: Partial<TaxProfileInput> = {
    grossIncome: overrides.grossIncome,
    payFrequency: overrides.payFrequency,
    filingStatus: profile.filingStatus ?? "single",
    customDeductions: overrides.customDeductions ?? 0,
  }

  for (const key of TAX_PROFILE_INPUT_KEYS) {
    const value = profile[key]
    if (value !== undefined) {
      ;(input as Record<string, unknown>)[key] = value
    }
  }

  return input as TaxProfileInput
}
