import {
  alabamaStrategy,
  arizonaStrategy,
  arkansasStrategy,
  californiaStrategy,
  connecticutStrategy,
  coloradoStrategy,
  delawareStrategy,
  genericFallbackStrategy,
  georgiaStrategy,
  hawaiiStrategy,
  idahoStrategy,
  illinoisStrategy,
  indianaStrategy,
  iowaStrategy,
  kansasStrategy,
  kentuckyStrategy,
  louisianaStrategy,
  maineStrategy,
  massachusettsStrategy,
  marylandStrategy,
  michiganStrategy,
  minnesotaStrategy,
  mississippiStrategy,
  missouriStrategy,
  montanaStrategy,
  nebraskaStrategy,
  newMexicoStrategy,
  newJerseyStrategy,
  newYorkStrategy,
  northCarolinaStrategy,
  northDakotaStrategy,
  ohioStrategy,
  oklahomaStrategy,
  oregonStrategy,
  pennsylvaniaStrategy,
  rhodeIslandStrategy,
  southCarolinaStrategy,
  utahStrategy,
  vermontStrategy,
  virginiaStrategy,
  washingtonDCStrategy,
  westVirginiaStrategy,
  wisconsinStrategy,
  zeroWageTaxStrategy,
} from "./states"
import type { StateCalculationResult, StateTaxStrategy, TaxContext } from "./types"

const stateStrategies: StateTaxStrategy[] = [
  alabamaStrategy,
  arizonaStrategy,
  arkansasStrategy,
  californiaStrategy,
  connecticutStrategy,
  delawareStrategy,
  illinoisStrategy,
  indianaStrategy,
  coloradoStrategy,
  georgiaStrategy,
  hawaiiStrategy,
  idahoStrategy,
  iowaStrategy,
  kansasStrategy,
  kentuckyStrategy,
  louisianaStrategy,
  maineStrategy,
  massachusettsStrategy,
  marylandStrategy,
  michiganStrategy,
  minnesotaStrategy,
  mississippiStrategy,
  missouriStrategy,
  montanaStrategy,
  nebraskaStrategy,
  newMexicoStrategy,
  newJerseyStrategy,
  newYorkStrategy,
  northCarolinaStrategy,
  northDakotaStrategy,
  ohioStrategy,
  oklahomaStrategy,
  oregonStrategy,
  pennsylvaniaStrategy,
  rhodeIslandStrategy,
  southCarolinaStrategy,
  vermontStrategy,
  utahStrategy,
  virginiaStrategy,
  washingtonDCStrategy,
  westVirginiaStrategy,
  wisconsinStrategy,
  zeroWageTaxStrategy,
  genericFallbackStrategy,
]

export function getStateTaxStrategy(context: TaxContext): StateTaxStrategy {
  return stateStrategies.find((strategy) => strategy.applies(context)) ?? genericFallbackStrategy
}

export function calculateStateTaxes(context: TaxContext): StateCalculationResult {
  return getStateTaxStrategy(context).calculate(context)
}
