//shared/schemas/taxProfile
import { z } from "zod"

/**
 * Tax Profile Domain Schema
 * --------------------------------------------------------
 * Defines tax-related configuration and deductions
 * for the user’s employment setup.
 *
 * Used in:
 * - Firestore tax profile documents
 * - Local cache persistence
 * - Tax calculation logic
 * --------------------------------------------------------
 */

// Base input (user form or partial updates)
export const Input = z.object({
  filingStatus: z
    .enum(["single", "marriedJoint", "marriedSeparate", "headOfHousehold"])
    .default("single"), 
  dependents: z.number().int().nonnegative().default(0),
  federalMultipleJobsCheckbox: z.boolean().optional(),
  federalStep3Credits: z.number().nonnegative().optional(),
  federalOtherIncome: z.number().nonnegative().optional(),
  federalDeductions: z.number().nonnegative().optional(),
  federalExempt: z.boolean().optional(),
  // Deprecated shared field kept only for backward compatibility with older saved profiles.
  stateWithholdingExemptions: z.number().int().nonnegative().optional(),
  marylandWithholdingExemptions: z.number().int().nonnegative().optional(),
  delawareWithholdingExemptions: z.number().int().nonnegative().optional(),
  hawaiiWithholdingExemptions: z.number().int().nonnegative().optional(),
  maineWithholdingExemptions: z.number().int().nonnegative().optional(),
  minnesotaWithholdingExemptions: z.number().int().nonnegative().optional(),
  nebraskaWithholdingExemptions: z.number().int().nonnegative().optional(),
  southCarolinaWithholdingExemptions: z.number().int().nonnegative().optional(),
  districtOfColumbiaWithholdingExemptions: z.number().int().nonnegative().optional(),
  vermontWithholdingExemptions: z.number().int().nonnegative().optional(),
  westVirginiaWithholdingExemptions: z.number().int().nonnegative().optional(),
  wisconsinWithholdingExemptions: z.number().int().nonnegative().optional(),
  alabamaExemptionCode: z.enum(["0", "S", "MS", "M", "H"]).optional(),
  arkansasExemptions: z.number().int().nonnegative().optional(),
  arkansasLowIncomeRates: z.boolean().optional(),
  idahoAllowances: z.number().int().nonnegative().optional(),
  idahoAdditionalWithholding: z.number().nonnegative().optional(),
  idahoExempt: z.boolean().optional(),
  iowaAllowanceAmount: z.number().nonnegative().optional(),
  iowaAdditionalWithholding: z.number().nonnegative().optional(),
  iowaExempt: z.boolean().optional(),
  iowaSpouseHasIncome: z.boolean().optional(),
  iowaMilitarySpouseExempt: z.boolean().optional(),
  kansasAllowanceRate: z.enum(["single", "joint"]).optional(),
  kansasAdditionalWithholding: z.number().nonnegative().optional(),
  kansasExempt: z.boolean().optional(),
  louisianaDeductionClaim: z.enum(["0", "1", "2"]).optional(),
  mississippiExemptionAmount: z.number().nonnegative().optional(),
  mississippiSpouseEmployed: z.boolean().optional(),
  missouriSpouseDoesNotWork: z.boolean().optional(),
  newMexicoHigherSingleRate: z.boolean().optional(),
  newMexicoExempt: z.boolean().optional(),
  newMexicoMilitarySpouseExempt: z.boolean().optional(),
  newMexicoNativeAmericanExempt: z.boolean().optional(),
  oklahomaAllowances: z.number().int().nonnegative().optional(),
  oklahomaHigherSingleRate: z.boolean().optional(),
  oklahomaAdditionalWithholding: z.number().nonnegative().optional(),
  oklahomaExempt: z.boolean().optional(),
  oklahomaMilitarySpouseExempt: z.boolean().optional(),
  oklahomaMilitaryIncomeExempt: z.boolean().optional(),
  arizonaWithholdingPercent: z.number().nonnegative().max(100).optional(),
  arizonaExempt: z.boolean().optional(),
  californiaRegularAllowances: z.number().int().nonnegative().optional(),
  californiaEstimatedDeductionAllowances: z.number().int().nonnegative().optional(),
  connecticutWithholdingCode: z.enum(["A", "B", "C", "D", "E", "F"]).optional(),
  connecticutAdditionalWithholding: z.number().nonnegative().optional(),
  connecticutReducedWithholding: z.number().nonnegative().optional(),
  connecticutNonresidentApportionmentPercent: z.number().nonnegative().max(100).optional(),
  connecticutFifteenDayExempt: z.boolean().optional(),
  coloradoDeductionAmount: z.number().nonnegative().optional(),
  districtOfColumbiaExempt: z.boolean().optional(),
  georgiaAllowanceCount: z.number().int().nonnegative().optional(),
  georgiaMarriedBothWorking: z.boolean().optional(),
  hawaiiHigherSingleRate: z.boolean().optional(),
  hawaiiCertifiedDisabled: z.boolean().optional(),
  hawaiiNonresidentMilitarySpouse: z.boolean().optional(),
  illinoisAllowanceLine1: z.number().int().nonnegative().optional(),
  illinoisAllowanceLine2: z.number().int().nonnegative().optional(),
  indianaPersonalExemptions: z.number().int().nonnegative().optional(),
  indianaDependentExemptions: z.number().int().nonnegative().optional(),
  indianaFirstTimeDependentExemptions: z.number().int().nonnegative().optional(),
  indianaAdoptedChildExemptions: z.number().int().nonnegative().optional(),
  indianaAdditionalStateWithholding: z.number().nonnegative().optional(),
  indianaAdditionalCountyWithholding: z.number().nonnegative().optional(),
  indianaNonresidentThirtyDayExempt: z.boolean().optional(),
  indianaNonresidentMilitarySpouseExempt: z.boolean().optional(),
  massachusettsExemptions: z.number().int().nonnegative().optional(),
  massachusettsBlindExemptions: z.number().int().min(0).max(2).optional(),
  massachusettsFullTimeStudentExempt: z.boolean().optional(),
  massachusettsMsrraExempt: z.boolean().optional(),
  massachusettsAdditionalWithholding: z.number().nonnegative().optional(),
  maineHigherSingleRate: z.boolean().optional(),
  michiganExemptions: z.number().int().nonnegative().optional(),
  montanaBothSpousesWorking: z.boolean().optional(),
  montanaExempt: z.boolean().optional(),
  nebraskaExempt: z.boolean().optional(),
  newJerseyRateTable: z.enum(["A", "B", "C", "D", "E"]).optional(),
  newJerseyAllowances: z.number().int().nonnegative().optional(),
  newJerseyExempt: z.boolean().optional(),
  newYorkAdditionalStateWithholding: z.number().nonnegative().optional(),
  newYorkExempt: z.boolean().optional(),
  northCarolinaAllowances: z.number().int().nonnegative().optional(),
  ohioExemptions: z.number().int().nonnegative().optional(),
  ohioAdditionalStateWithholding: z.number().nonnegative().optional(),
  ohioResidentMilitaryOutsideOhioExempt: z.boolean().optional(),
  ohioNonresidentMilitaryExempt: z.boolean().optional(),
  ohioNonresidentMilitarySpouseExempt: z.boolean().optional(),
  ohioStatutoryExempt: z.boolean().optional(),
  oregonAllowances: z.number().int().nonnegative().optional(),
  oregonAdditionalWithholding: z.number().nonnegative().optional(),
  oregonHigherSingleRate: z.boolean().optional(),
  oregonExempt: z.boolean().optional(),
  southCarolinaExempt: z.boolean().optional(),
  westVirginiaLowerRateElection: z.boolean().optional(),
  virginiaPersonalExemptions: z.number().int().nonnegative().optional(),
  virginiaAgeBlindExemptions: z.number().int().nonnegative().optional(),
  virginiaExempt: z.boolean().optional(),
  retirement401kType: z.enum(["traditional", "roth"]).optional(),
  retirement401kPercent: z.number().nonnegative().optional(),
  retirement401kFlat: z.number().nonnegative().optional(),
  insurancePremium: z.number().nonnegative().optional(),
  insurancePreTax: z.boolean().default(true),
  state: z.string().min(2),
  residenceState: z.string().min(2).optional(),
  workState: z.string().min(2).optional(),
  residenceCounty: z.string().min(1).optional(),
  workCounty: z.string().min(1).optional(),
  residenceCity: z.string().min(1).optional(),
  workCity: z.string().min(1).optional(),
  postalCode: z.string().min(3).optional(),
  schoolDistrictId: z.string().min(1).optional(),
  localTaxJurisdictionIds: z.array(z.string().min(1)).default([]),
  ohioSchoolDistrictNumber: z.string().regex(/^\d{4}$/).optional(),
  ohioSchoolDistrictIncomeTaxRate: z.number().nonnegative().max(99.99).optional(),
  ohioMunicipalIncomeTaxRate: z.number().nonnegative().max(99.99).optional(),
  ohioJeddJedzIncomeTaxRate: z.number().nonnegative().max(99.99).optional(),
  oregonMetroLocation: z.boolean().optional(),
  oregonMultnomahCountyLocation: z.boolean().optional(),
  oregonMetroWithholdingElection: z.enum(["auto", "opt_in", "opt_out"]).optional(),
  oregonPfaWithholdingElection: z.enum(["auto", "opt_in", "opt_out"]).optional(),
  newYorkLocality: z
    .enum(["new_york_city_resident", "yonkers_resident", "yonkers_nonresident"])
    .optional(),
  newYorkWithholdingExemptions: z.number().int().nonnegative().optional(),
  pennsylvaniaResidentPsdCode: z.string().regex(/^\d{6}$/).optional(),
  pennsylvaniaResidentEitRate: z.number().nonnegative().max(99.99).optional(),
  pennsylvaniaWorkPsdCode: z.string().regex(/^\d{6}$/).optional(),
  pennsylvaniaWorkNonResidentEitRate: z.number().nonnegative().max(99.99).optional(),
  rhodeIslandAllowances: z.number().int().nonnegative().max(10).optional(),
  rhodeIslandAdditionalWithholding: z.number().nonnegative().optional(),
  rhodeIslandExemptStatus: z.enum(["EXEMPT", "EXEMPT-MS"]).optional(),
  reciprocityElection: z.boolean().optional(),
  multiStateWorker: z.boolean().optional(),
  pfmlPercent: z.number().nonnegative().optional(),
  waCaresPercent: z.number().nonnegative().optional(),
  additionalFederalWithholding: z.number().nonnegative().optional(),
  additionalStateWithholding: z.number().nonnegative().optional(),
})

// Full persisted schema (includes metadata)
export const Schema = Input.extend({
  updatedAt: z.string().datetime().optional(),
})

// Inferred types
export type InputType = z.infer<typeof Input>
export type Type = z.infer<typeof Schema>
